apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Hello from ConfigMap</title></head>
    <body style="background-color:#222; color: white; text-align:center;">
      <h1>🚀 Welcome to Kubernetes with NGINX!</h1>
      <p>This page is served from a ConfigMap, not from the Docker image.</p>
    </body>
    </html>
